# Generated by Django 3.1.4 on 2020-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='phone_num',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
